### ISSUE TITLE
Distribute wheels on PyPI

### ISSUE THREAD

**Issue by wiggin15** [kodonnell/qoi#1]
Hi. Thanks for this project!

I see you are only distributing a "source distribution" on PyPI which contains the C files that needs to be compiled. This means you have to have a C compiler on your machine in order for installation to work (not always the case on Windows), and generally may complicate the installation.

[Python wheels](https://pythonwheels.com/) are a great way to distribute precompiled Python C extensions. Can you consider uploading wheels to PyPI?

There are several projects that can help you automate the creation of wheels for different platforms, see [cbuildwheel](https://github.com/pypa/cibuildwheel) for example.

**Comment by wiggin15** [comment]
I just noticed it's in your TODO list in the README.
Well, now there's an open issue :)

**Comment by kodonnell** [comment]
> I just noticed it's in your TODO list in the README. Well, now there's an open issue :)

Nice! Do you have any experience with cibuildwheel (or Github actions for python)? If so, I'd love a PR = ) Otherwise I'll aim to get to this in the next few days hopefully? But yes, definitely agree wheels are worth doing.

**Comment by kodonnell** [comment]
OK, I think this is working on a variety of platforms (see https://github.com/kodonnell/qoi/releases/tag/v0.0.8). Learned a lot which was fun, thought there are still a few things lurking around that need fixing. @wiggin15 I'll close for now as I think it's complete, but feel free to re-open if I've missed anything!
