### ISSUE TITLE
Fails to install on Mac OS with Apple M1

### ISSUE THREAD

**Issue by bicsi** [kodonnell/qoi#14]
Hello,

Currently the library fails to install on Mac OS with Apple M1 Silicon, because of the numpy dependency. This is due to the (outdated) versions of numpy in `pyproject.toml` file. I managed to install from source by changing the contents of the file (adding "numpy>=1.24.2" in the `requires` section of `pyproject.toml`). 

Could you please bump the version of numpy to fix this issue?

**Comment by kodonnell** [comment]
Thanks @bicsi  - working on it now.

**Comment by kodonnell** [comment]
Hi @bicsi - once [0.3.0 has finished](https://github.com/kodonnell/qoi/actions/runs/4452368727), can you try a new pip install and see if it works on your mac? Much appreciated.

**Comment by kodonnell** [comment]
Closing, but feel free to re-open if it's still an issue.
