### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by ivanstepanovftw** [kodonnell/qoi#25]
Hello! Thank you for your library. Can you please clarify in the README about input shape? I assume it is (height, width, channels), where height and width is limited up to 400000000 pixels total (h*w) ([link](https://github.com/phoboslab/qoi/blob/d4fc9d1edf44e5d7e76a9ee64ef08ae4c5c2efda/qoi.h#L332C39-L332C48)), and channels are either 3 or 4 dimension of RGBA ([link](https://github.com/phoboslab/qoi/blob/d4fc9d1edf44e5d7e76a9ee64ef08ae4c5c2efda/qoi.h#L407-L409)).

**Comment by kodonnell** [comment]
Cool, made a note of HWC ordering in the example = ) Re-open if you need more.
