### ISSUE TITLE
Read only ndarray is not permitted while writing it to a file

### ISSUE THREAD

**Issue by ivanstepanovftw** [kodonnell/qoi#26]
To reproduce:
```python
import qoi
from PIL import Image
image_filepath = "something.png"
prepared_image_filepath = "something.qoi"
image = Image.open(image_filepath).convert('RGB')
image_qoi = np.asarray(image)
_ = qoi.write(prepared_image_filepath, image_qoi)
```
Output:
```plaintext
Traceback (most recent call last):
...
  File "main.py", line 452, in __init__
    _ = qoi.write(prepared_image_filepath, image_qoi)
  File "src/qoi/qoi.pyx", line 31, in qoi.qoi.write
  File "<stringsource>", line 663, in View.MemoryView.memoryview_cwrapper
  File "<stringsource>", line 353, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
```
Version:
```
Python 3.10.13
numpy                        1.26.4
qoi                          0.5.0
```

**Comment by kodonnell** [comment]
OK, so the easy fix is using `np.array` not `np.asarray` - https://stackoverflow.com/questions/14415741/what-is-the-difference-between-np-array-and-np-asarray

It seems like PIL reads in read-only mode. Do you want to look into some possible solutions? I could just check for the WRITEABLE flag on the array and either throw a (more useful) exception, or take a copy of it.

**Comment by kodonnell** [comment]
FYI pushed an xfailing test for this.

**Comment by ivanstepanovftw** [comment]
I just do not want to copy whole image, as np.array copies whole image and np.asarray doesn't. It is also not expected that array should be writable - why is it required to be writable?

**Comment by ivanstepanovftw** [comment]
Maybe there should be `const` added to the image argument somewhere?

**Comment by kodonnell** [comment]
> Maybe there should be `const` added to the image argument somewhere?

Oh I should have checked this first! I just figured this out too and it fixes the issue - ta. I'll wait for it to build and all the tests pass, and if so, I'll push a new release.

**Comment by synodriver** [comment]
Sorry for the late reply. The const in Cython means wether the argument is mutable does not matter, mostly used to deal with ```bytes```, which is has a readonly buffer. I just forgot the ndarray objects can also have a readonly buffer!
