### ISSUE TITLE
Incompatibility with `numpy` 2.0.0 -> error on import

### ISSUE THREAD

**Issue by MikiP98** [kodonnell/qoi#27]
Importing `QOI` package while having `Numpy 2.0.0` installed causes this error:
```
Traceback (most recent call last):
  File "D:\...\MultiScaler-Plus\src\standalone.py", line 14, in <module>
    import qoi
  File "C:\Users\...\AppData\Roaming\Python\Python312\site-packages\qoi\__init__.py", line 2, in <module>
    from qoi.qoi import QOIColorSpace, decode, encode, read, write
  File "src/qoi/qoi.pyx", line 1, in init qoi.qoi
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by kodonnell** [comment]
Thanks, verified. Looks like numpy 2 is release as of a week ago, and these release notes look pretty relevant! 

![image](https://github.com/kodonnell/qoi/assets/8204904/b302e8b6-0c82-434b-9273-96d7c9ec5041)

I'll have a quick look at how scipy does things (which is where most of my setup.py is copied from).

**Comment by kodonnell** [comment]
Cool, v0.7.0 should now support numpy>=2.0.0 (and older versions). Once the github action has run (assuming it succeeds), it should publish - can you check? Thanks.

**Comment by MikiP98** [comment]
Neat! 
Thanks a lot!
Have a nice day :)

**Comment by MikiP98** [comment]
Older Numpy still works with no issues, newer does not crash on QOI import but crashes on different package import...
Time to make a new issue on different repo :/

Thanks for quick response!
Have a nice day! 😺

**Comment by MikiP98** [comment]
Found the new culprit: Torch
Issue already there, just have to wait.
