### ISSUE TITLE
Approximate with GraphicsMagick and/or G'MIC

### ISSUE THREAD

**Issue by dumblob** [kodonnell/qoi#4]
I wonder whether the current code could be rewritten (approximated?) using GraphicsMagick and/or G'MIC without any Python nor any otther dependencies to make it accessible from shell without any further dependencies.

I think we can assume gm and gmic will both soon support QOI (both decode & encode). So let's take it for granted.

Then the only question is whether it's worth rewriting (or approximating) the sampling only using what gm/gmic/both offer in command line is possible?

Thoughts?

**Comment by kodonnell** [comment]
Sorry, I'm not entirely sure what you're proposing = ) This is currently a python library (mostly for use with the popular PIL and OpenCV) so getting rid of python might defeat the point! Or do you just mean the benchmarking script? Again, for now since I'm focused on performance within Python, it probably doesn't make sense.

Sorry if I've completely missed the point!

**Comment by dumblob** [comment]
Sorry for not being clear.

>This is currently a python library (mostly for use with the popular PIL and OpenCV) so getting rid of python might defeat the point!

My suggestion is to provide a standalone encoder application from this library. And when at it, I wonder whether this app could be a shell script using graphicsmagick and/or gmic internally for all the needed computations (read image, sample etc. the read image, and then write down QOI-encoded image). I'm asking as this would make this image format fully portable with no packaging effort (because shell runs on Windows, macOS, Android, iOS, Linux, BSDs, etc. and so does graphicsmagick & gmic).

Does that make sense?

**Comment by tushar-deepsource** [comment]
@dumblob This project is mostly to be able to use qoi in Python scripts (the code is written in C and Python, both of which run on almost all desktop platforms as well.)

If the goal is to make a portable CLI for this, you should check out the C source instead: https://github.com/phoboslab/qoi

**Comment by dumblob** [comment]
Actually I'm interested only in the lossy "extension" of QOI your utility supports. Therefore the C source of QOI will not cut it for me :cry:.

**Comment by kodonnell** [comment]
There are a lot of tools that now support QOI - see https://github.com/phoboslab/qoi#qoi-support-in-other-software . ImageMagick is included - not sure if that related to GraphicsMagick? My lossy 'extension' should be able to be replicated in any tool - just downsize before you encode = )

Anyway, given this project is about using QOI in Python as @tushar-deepsource mentioned, are you OK if we close this issue?

**Comment by dumblob** [comment]
>My lossy 'extension' should be able to be replicated in any tool - just downsize before you encode = )

Yep, this was my question - if and how to replicate it using only graphicsmagick and/or G'MIC.

> Anyway, given this project is about using QOI in Python as @tushar-deepsource mentioned, are you OK if we close this issue?

Feel free to do so. This issue was really just about getting some feedback from people who would be interested in having your 'extension' implemented purely using graphicsmagick and/or G'MIC.
