### ISSUE TITLE
Import Fails on M1 Mac (Apple Silicon)

### ISSUE THREAD

**Issue by John-P** [kodonnell/qoi#9]
The package will install on an M1 Mac (Apple Silicon) with pip but importing raises the following exception:

```python
Python 3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:24:38) 
[Clang 12.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import qoi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john/miniforge3/envs/test-qoi/lib/python3.9/site-packages/qoi/__init__.py", line 2, in <module>
    from qoi.qoi import QOIColorSpace, decode, encode, read, write
  File "src/qoi/qoi.pyx", line 1, in init qoi.qoi
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

The package appears to work just fine on other systems. I am using numpy version 1.21.6 on an M1 MacBook air to produce this error.

**Comment by kodonnell** [comment]
Thanks @John-P - looks like I need to get cleverer with numpy builds. Or ... just copy how scipy does it = ) Trying with it out now [here](/kodonnell/qoi/tree/feature/fixnumpy). I'll push to pypi if it works.

**Comment by kodonnell** [comment]
Hopefully v0.1.2 builds and pushes - can you try install that and check it works? Thanks

**Comment by kodonnell** [comment]
Feel free to re-open if the latest builds haven't fixed this.
